/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mastermind;

import java.util.Random;
import javax.swing.JOptionPane;



/**
 *
 * @author Antonio
 */
public class Mastermind extends javax.swing.JFrame {

    //Crear variables y objetos
    //variables para todo el juego
    int inicioFor = 0;
    int finalFor = 3;
    //variables para el codificador
    Random generadorNumeros = new Random();
    char numeros;
    char inicializarNumero = '0';
    String codificador = "";

    //variables para las fichas
    int rojas = 0;
    int blancas = 0;
    String sinFichas = "0";
    //variables para el descodificador
    String cadena = "";
    int numeroIntento = 0;
    int ultimoIntento = 10;

    
    
    
    public Mastermind() {
        initComponents();
        //Programa
        //inicializar campos
        jTextField1Rojas.setText(sinFichas);
        jTextField1Blancas.setText(sinFichas); 
        //crear el codigo secreto
        //le sumamos el codigo char del 0
        for(int i=inicioFor; i<=finalFor; i++){
            numeros = (char)(generadorNumeros.nextInt(8) + inicializarNumero);
            int q=0;
            if(i != inicioFor){
                for( q=i-1; q>=inicioFor; q--){
                    if(numeros == codificador.charAt(q)){
                        numeros = (char)(generadorNumeros.nextInt(8) + inicializarNumero);
                        q = i;
                    }
                    
                }
            }
            codificador += numeros;
        }
        jTextField1Patron.setText(codificador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Descodificador = new javax.swing.JPanel();
        jLabel2Descodificador = new javax.swing.JLabel();
        jLabel13Rojas = new javax.swing.JLabel();
        jLabel14Blancas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Descodificador = new javax.swing.JTextArea();
        jButton1Comprobar = new javax.swing.JButton();
        jTextField1Rojas = new javax.swing.JTextField();
        jTextField1Blancas = new javax.swing.JTextField();
        jTextField1MeterCodigo = new javax.swing.JTextField();
        jPanel2Codificador = new javax.swing.JPanel();
        jLabel1Patron = new javax.swing.JLabel();
        jTextField1Patron = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1Descodificador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2Descodificador.setText("Descodificador");

        jLabel13Rojas.setText("Rojas");

        jLabel14Blancas.setText("Blancas");

        jTextArea1Descodificador.setColumns(20);
        jTextArea1Descodificador.setRows(5);
        jScrollPane1.setViewportView(jTextArea1Descodificador);

        jButton1Comprobar.setText("Comprobar");
        jButton1Comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1DescodificadorLayout = new javax.swing.GroupLayout(jPanel1Descodificador);
        jPanel1Descodificador.setLayout(jPanel1DescodificadorLayout);
        jPanel1DescodificadorLayout.setHorizontalGroup(
            jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1DescodificadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1DescodificadorLayout.createSequentialGroup()
                        .addComponent(jLabel2Descodificador)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1MeterCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1DescodificadorLayout.createSequentialGroup()
                        .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1Rojas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13Rojas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14Blancas)
                            .addComponent(jTextField1Blancas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1Comprobar))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1DescodificadorLayout.setVerticalGroup(
            jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1DescodificadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2Descodificador)
                    .addComponent(jTextField1MeterCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1Comprobar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1DescodificadorLayout.createSequentialGroup()
                        .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13Rojas)
                            .addComponent(jLabel14Blancas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1Rojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1Blancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Codificador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2Codificador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1Patron.setText("Patron");
        jPanel2Codificador.add(jLabel1Patron, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));
        jPanel2Codificador.add(jTextField1Patron, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2Codificador, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1Descodificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1Descodificador, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2Codificador, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ComprobarActionPerformed
        //introduccion del codigo del jugador
        jTextField1Rojas.setText(sinFichas);
        jTextField1Blancas.setText(sinFichas); 
        blancas = Integer.valueOf(sinFichas);
        rojas = Integer.valueOf(sinFichas);

        cadena = jTextField1MeterCodigo.getText();
        if(numeroIntento <= ultimoIntento){
            for(int j=inicioFor; j<=finalFor; j++){
                for(int k=inicioFor; k<=finalFor; k++){
                    if(codificador.charAt(j) == (cadena.charAt(k))){
                        blancas++;
                        if(codificador.charAt(k) == (cadena.charAt(k))){
                            rojas++;
                        }
                    }

                }
            }
            numeroIntento++;
        }
        else{
            new VentanaPerdedor(this, true).setVisible(true);
        }
        if(blancas > Integer.valueOf(sinFichas)){
            blancas -= rojas;
        }
        jTextField1Rojas.setText(String.valueOf(rojas));
        jTextField1Blancas.setText(String.valueOf(blancas)); 
        jTextArea1Descodificador.append(cadena + "\n");
        
        //terminar juego el mensaje no puede ir aky
        if(cadena.equals(codificador)){
            new VentanaGanador(this, true).setVisible(true);                
        }
    }//GEN-LAST:event_jButton1ComprobarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mastermind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Comprobar;
    private javax.swing.JLabel jLabel13Rojas;
    private javax.swing.JLabel jLabel14Blancas;
    private javax.swing.JLabel jLabel1Patron;
    private javax.swing.JLabel jLabel2Descodificador;
    private javax.swing.JPanel jPanel1Descodificador;
    private javax.swing.JPanel jPanel2Codificador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1Descodificador;
    private javax.swing.JTextField jTextField1Blancas;
    private javax.swing.JTextField jTextField1MeterCodigo;
    private javax.swing.JTextField jTextField1Patron;
    private javax.swing.JTextField jTextField1Rojas;
    // End of variables declaration//GEN-END:variables

}



//factorioal
/*
try{
                int numero = Integer.valueOf(jTextField1Patron.getText());
                float resultado = 1;
                for(int i=numero; i<=2; i--){
                    resultado *= i;
                    
                }
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Introducir solo numeros\n" + "ERROR " + ex.getMessage());
                ex.printStackTrace();
            }
*/