/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mastermind;

import java.util.Random;



/**
 *
 * @author Antonio
 */
public class Mastermind extends javax.swing.JFrame {

    //Crear variables y objetos
    //variables para todo el juego
    int inicioFor = 0;
    int finalFor = 3;
    //variables para el codificador
    Random generadorNumeros = new Random();
    String numeros;
    String codificador = "";
    //para que no se repita
    //tendre que quitar estas variables
    int primerAleatorio = 0;
    int segundoAleatorio = 0;
    int tercerAleatorio = 0;
    int cuartoAleatorio = 0;

    //variables para las fichas
    int rojas = 0;
    int blancas = 0;
    String sinFichas = "0";
    //variables para el descodificador
    String cadena = "";

    
    
    
    public Mastermind() {
        initComponents();
        //Programa
        //inicializar campos
        jTextField1Rojas.setText(sinFichas);
        jTextField1Blancas.setText(sinFichas); 
        //crear el codigo secreto
        for(int i=inicioFor; i<=finalFor; i++){
            numeros = String.valueOf(generadorNumeros.nextInt(8));
            codificador += String.valueOf(numeros);
            
            //pasar el char a entero no al valor unicode
            for(int q=i; q>=inicioFor; q--){
                if(codificador.charAt(q) == numeros.charAt(i)){
                    numeros = String.valueOf(generadorNumeros.nextInt(8));
                }
            }
            jTextField1Patron.setText(codificador);
            
           
        /* DE ESTA MANERA FUNCIONA
            switch(i){
                case 0:{
                    primerAleatorio = numeros;
                    break;
                }
                case 1:{
                    segundoAleatorio = numeros;
                    while(primerAleatorio == segundoAleatorio){
                        numeros = generadorNumeros.nextInt(8); 
                        segundoAleatorio = numeros;
                    }
                    break;
                
                }
                case 2:{
                    tercerAleatorio = numeros;
                    while(tercerAleatorio == primerAleatorio || tercerAleatorio == segundoAleatorio){
                        numeros = generadorNumeros.nextInt(8); 
                        tercerAleatorio = numeros;
                    }
                    break;
                }
                case 3:{
                    cuartoAleatorio = numeros;
                    while(cuartoAleatorio == primerAleatorio || cuartoAleatorio == segundoAleatorio 
                            || cuartoAleatorio == tercerAleatorio){
                        numeros = generadorNumeros.nextInt(8); 
                        cuartoAleatorio = numeros;
                    }
                    break;
                }
            }
            
        codificador += String.valueOf(numeros);
        jTextField1Patron.setText(codificador);
        */
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Descodificador = new javax.swing.JPanel();
        jLabel2Descodificador = new javax.swing.JLabel();
        jLabel13Rojas = new javax.swing.JLabel();
        jLabel14Blancas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Descodificador = new javax.swing.JTextArea();
        jButton1Comprobar = new javax.swing.JButton();
        jTextField1Rojas = new javax.swing.JTextField();
        jTextField1Blancas = new javax.swing.JTextField();
        jTextField1MeterCodigo = new javax.swing.JTextField();
        jPanel2Codificador = new javax.swing.JPanel();
        jLabel1Patron = new javax.swing.JLabel();
        jTextField1Patron = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1Descodificador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2Descodificador.setText("Descodificador");

        jLabel13Rojas.setText("Rojas");

        jLabel14Blancas.setText("Blancas");

        jTextArea1Descodificador.setColumns(20);
        jTextArea1Descodificador.setRows(5);
        jScrollPane1.setViewportView(jTextArea1Descodificador);

        jButton1Comprobar.setText("Comprobar");
        jButton1Comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1DescodificadorLayout = new javax.swing.GroupLayout(jPanel1Descodificador);
        jPanel1Descodificador.setLayout(jPanel1DescodificadorLayout);
        jPanel1DescodificadorLayout.setHorizontalGroup(
            jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1DescodificadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1DescodificadorLayout.createSequentialGroup()
                        .addComponent(jLabel2Descodificador)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1MeterCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1DescodificadorLayout.createSequentialGroup()
                        .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1Rojas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13Rojas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14Blancas)
                            .addComponent(jTextField1Blancas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1Comprobar))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1DescodificadorLayout.setVerticalGroup(
            jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1DescodificadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2Descodificador)
                    .addComponent(jTextField1MeterCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1Comprobar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1DescodificadorLayout.createSequentialGroup()
                        .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13Rojas)
                            .addComponent(jLabel14Blancas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1DescodificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1Rojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1Blancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Codificador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2Codificador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1Patron.setText("Patron");
        jPanel2Codificador.add(jLabel1Patron, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));
        jPanel2Codificador.add(jTextField1Patron, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2Codificador, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1Descodificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1Descodificador, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2Codificador, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ComprobarActionPerformed
        //introduccion del codigo del jugador
        jTextField1Rojas.setText(sinFichas);
        jTextField1Blancas.setText(sinFichas); 
        blancas = Integer.valueOf(sinFichas);
        rojas = Integer.valueOf(sinFichas);

        cadena = jTextField1MeterCodigo.getText();
        for(int j=inicioFor; j<=finalFor; j++){
            for(int k=inicioFor; k<=finalFor; k++){
                if(codificador.charAt(j)==(cadena.charAt(k))){
                    blancas++;
                    if(codificador.charAt(k)==(cadena.charAt(k))){
                        rojas++;
                    }
                }

            }
        }
        if(blancas > Integer.valueOf(sinFichas)){
            blancas -= rojas;
        }
        jTextField1Rojas.setText(String.valueOf(rojas));
        jTextField1Blancas.setText(String.valueOf(blancas)); 
        jTextArea1Descodificador.append(cadena + "\n");
        
        //terminar juego
        
        if(rojas >= 4){
            new VentanaGanador(this, true).setVisible(true);
        }
    }//GEN-LAST:event_jButton1ComprobarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mastermind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Comprobar;
    private javax.swing.JLabel jLabel13Rojas;
    private javax.swing.JLabel jLabel14Blancas;
    private javax.swing.JLabel jLabel1Patron;
    private javax.swing.JLabel jLabel2Descodificador;
    private javax.swing.JPanel jPanel1Descodificador;
    private javax.swing.JPanel jPanel2Codificador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1Descodificador;
    private javax.swing.JTextField jTextField1Blancas;
    private javax.swing.JTextField jTextField1MeterCodigo;
    private javax.swing.JTextField jTextField1Patron;
    private javax.swing.JTextField jTextField1Rojas;
    // End of variables declaration//GEN-END:variables

}
